name: Sync ACG to Consumer Repos

on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'Target repos (default: all)'
        default: 'all'
        type: choice
        options: ['all', 'acg-tooling-consumer', 'acg-tooling-consumer1']

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [acg-tooling-consumer, acg-tooling-consumer1]
      fail-fast: false

    steps:
    - name: Skip if not selected
      if: inputs.repos != 'all' && inputs.repos != matrix.repo
      run: exit 0

    - name: Checkout ACG repo
      uses: actions/checkout@v4
      with:
        path: acg

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: loy-misquith-frequence/${{ matrix.repo }}
        token: ${{ secrets.ACG_SYNC_TOKEN }}
        path: target

    - name: Sync Claude config
      run: |
        cd target
        rsync -av --delete ../acg/.claude/ .claude/

    - name: Sync AI context
      run: |
        cd target
        mkdir -p ai

        # First sync common/shared AI context (excluding repo-specific folders)
        echo "Syncing common AI context..."
        rsync -av --delete \
          --exclude=tickets/ \
          --exclude=*_context/ \
          ../acg/ai/ ai/

        # Then sync repo-specific context if it exists
        REPO_CONTEXT="../acg/ai/${{ matrix.repo }}_context"
        if [ -d "$REPO_CONTEXT" ] && [ "$(ls -A $REPO_CONTEXT)" ]; then
          echo "Syncing repo-specific context: ${{ matrix.repo }}_context"
          rsync -av --exclude=tickets/ "$REPO_CONTEXT/" ai/
        else
          echo "No repo-specific context found for ${{ matrix.repo }}"
        fi

    - name: Commit & Push
      run: |
        cd target
        git config user.name "ACG Sync Bot"
        git config user.email "acg-bot@frequence.com"

        git add .claude ai
        if ! git diff --cached --quiet; then
          git commit -m "🤖 Update ACG tooling from central repo"
          git push origin master
        fi
